server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-vehiculos
          uri: lb://ms-vehiculos
          predicates:
            - Path=/vehiculo/**
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/usuario/**
        - id: ms-estadias
          uri: lb://ms-estadias
          predicates:
            - Path=/estadia/**
        - id: ms-registros
          uri: lb://ms-registros
          predicates:
            - Path=/registro/**    
