server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
          config:
      enabled: true
      uri: http://localhost:8081
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-vehiculos
          uri: lb://ms-vehiculos
          predicates:
            - Path=/vehiculo/**
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/usuario/**
        - id: ms-estadias
          uri: lb://ms-estadias
          predicates:
            - Path=/estadia/**
        - id: ms-registros
          uri: lb://ms-registros
          predicates:
            - Path=/registro/**    
